### ISSUE TITLE
photolibraryd holds a lock on the database

### ISSUE THREAD

**Issue by coppit** [koraktor/gallerist#4]
First, thanks a ton for writing this. Did you reverse engineer the DBs? I have a script to back up my highly rated iPhoto photos using the old AlbumData.xml, and I'd like to update it for Photos.app. Your code will help a ton to figure it out.

After copying the database, would it be possible to force clear the locks? I'm getting errors because the DB is being locked by photolibraryd:

$ fuser /Volumes/Data/Pictures/Photos\ Library.photoslibrary/Database/*.apdb
/Volumes/Data/Pictures/Photos Library.photoslibrary/Database/BigBlobs.apdb: 
/Volumes/Data/Pictures/Photos Library.photoslibrary/Database/History.apdb: 
/Volumes/Data/Pictures/Photos Library.photoslibrary/Database/ImageProxies.apdb: 504
/Volumes/Data/Pictures/Photos Library.photoslibrary/Database/Library.apdb:  504
/Volumes/Data/Pictures/Photos Library.photoslibrary/Database/Properties.apdb:  504

(coppit @ dcoppit-macbook-pro.local) : /Volumes/Data/Pictures/Photos Library.photoslibrary/Database
$ ps -p 504
  PID TTY           TIME CMD
  504 ??         3:02.18 /System/Library/PrivateFrameworks/PhotoLibraryPrivate.framework/Versions/A/Support/photolibraryd

**Comment by koraktor** [comment]
That’s the main reason why database files are copied in the first place. AFAIK it’s not possible to copy / unlock the databases while `photolibraryd` locks them.

If you find a way, please let me know.

**Comment by coppit** [comment]
> That’s the main reason why database files are copied in the first place.

Oh, I didn't realize that. In that case I guess this is a bug report.
Despite the copying, I still got a stack trace regarding some sort of
locking. After killing the photolibraryd process, I don't see the problem
any more.

$ gallerist /Volumes/Data/Pictures/Photos\ Library.photoslibrary
I, [2015-06-19T23:33:21.462045 #2657]  INFO -- : Loading library from
"/Volumes/Data/Pictures/Photos Library.photoslibrary"
2015-06-19 23:33:21 - SQLite3::BusyException - database is locked:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/statement.rb:108:in
`step'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/statement.rb:108:in
`block in each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/statement.rb:107:in
`loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/statement.rb:107:in
`each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:158:in
`to_a'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:158:in
`block in execute'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:95:in
`prepare'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:134:in
`execute'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:484:in
`transaction'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/library.rb:57:in
`copy_tmp_db'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/library.rb:39:in
`copy_base_db'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/app.rb:76:in
`library'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/app.rb:152:in
`block in <class:App>'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in
`call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in
`block in compile!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`[]'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in
`block (3 levels) in route!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in
`route_eval'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in
`block (2 levels) in route!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in
`block in process_route'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in
`catch'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in
`process_route'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in
`block in route!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in
`each'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in
`route!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in
`block in dispatch!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
`block in invoke'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
`catch'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
`invoke'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in
`dispatch!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in
`block in call!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
`block in invoke'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
`catch'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
`invoke'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in
`call!'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in
`call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in
`call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in
`call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in
`call'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/middleware/raise_warmup_exceptions.rb:13:in
`call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in
`call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in
`call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in
`block in call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in
`synchronize'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in
`call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in
call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in`each'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/mock.rb:74:in`request'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/mock.rb:56:in `get'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/config.ru:12:in`block (2
levels) in <main>'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:148:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:148:in`to_app'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/config.ru:23:in `<main>'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in`eval'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in
`new_from_string'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in
`parse_file'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:299:in
`build_app_and_options_from_config'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:208:in`app'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:336:in
`wrapped_app'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:272:in`start'
/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
/Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/bin/gallerist:52:in`<top
(required)>'
/usr/bin/gallerist:23:in `load'
/usr/bin/gallerist:23:in`<main>'
- \- - [19/Jun/2015:23:33:25 -0400] "GET / " 500 754 4.2647
  I, [2015-06-19T23:33:25.757268 #2657]  INFO -- : listening on addr=
  0.0.0.0:9292 fd=9
  I, [2015-06-19T23:33:25.757372 #2657]  INFO -- : worker=0 spawning...
  I, [2015-06-19T23:33:25.758584 #2657]  INFO -- : worker=1 spawning...
  I, [2015-06-19T23:33:25.759175 #2657]  INFO -- : worker=2 spawning...
  I, [2015-06-19T23:33:25.759803 #2658]  INFO -- : worker=0 spawned pid=2658
  I, [2015-06-19T23:33:25.760119 #2659]  INFO -- : worker=1 spawned pid=2659
  I, [2015-06-19T23:33:25.760620 #2658]  INFO -- : worker=0 ready
  I, [2015-06-19T23:33:25.760682 #2659]  INFO -- : worker=1 ready
  I, [2015-06-19T23:33:25.761705 #2657]  INFO -- : worker=3 spawning...
  I, [2015-06-19T23:33:25.762389 #2657]  INFO -- : master process ready
  I, [2015-06-19T23:33:25.762894 #2660]  INFO -- : worker=2 spawned pid=2660
  I, [2015-06-19T23:33:25.763497 #2661]  INFO -- : worker=3 spawned pid=2661
  I, [2015-06-19T23:33:25.763652 #2660]  INFO -- : worker=2 ready
  I, [2015-06-19T23:33:25.764198 #2661]  INFO -- : worker=3 ready
  ^[[A2015-06-19 23:34:56 - ActiveRecord::ConnectionNotEstablished - No
  connection pool for Gallerist::Album:
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:566:in
  `retrieve_connection'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:113:in
  `retrieve_connection'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:87:in
  `connection'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/associations/join_dependency.rb:96:in
  `initialize'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation/query_methods.rb:1040:in
  `new'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation/query_methods.rb:1040:in
  `build_joins'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation/query_methods.rb:866:in
  `build_arel'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation/query_methods.rb:858:in
  `arel'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation.rb:638:in
  `exec_queries'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation.rb:514:in
  `load'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation.rb:243:in
  `to_a'
  /Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation/delegation.rb:46:in
  `each'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/../../views/index.erb:9:in
  `block in singleton class'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/../../views/index.erb:-6:in
  `instance_eval'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/../../views/index.erb:-6:in
  `singleton class'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/../../views/index.erb:-8:in
  `__tilt_70194399929440'
  /Library/Ruby/Gems/2.0.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
  /Library/Ruby/Gems/2.0.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in
  `evaluate'
  /Library/Ruby/Gems/2.0.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in
  `render'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:666:in `erb'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/app.rb:160:in
  `block in class:App'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in
  `block in compile!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in
  `block (3 levels) in route!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in
  `route_eval'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in
  `block (2 levels) in route!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in
  `block in process_route'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in
  `catch'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in
  `process_route'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in
  `block in route!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in
  `each'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in
  `route!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in
  `block in dispatch!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
  `block in invoke'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
  `catch'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
  `invoke'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in
  `dispatch!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in
  `block in call!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
  `block in invoke'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
  `catch'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in
  `invoke'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in
  `call!'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in`call'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/gallerist/middleware/raise_warmup_exceptions.rb:13:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in
  `block in call'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in
  `synchronize'
  /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in
  `call'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in`block in
  call'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in`call'
  /Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in
  `process_client'
  /Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in
  `worker_loop'
  /Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in
  `spawn_missing_workers'
  /Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in
  `start'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/lib/rack/handler/unicorn.rb:23:in
  `run'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:286:in`start'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
  /Library/Ruby/Gems/2.0.0/gems/gallerist-0.1.0/bin/gallerist:52:in`<top
  (required)>'
  /usr/bin/gallerist:23:in `load'
  /usr/bin/gallerist:23:in`<main>'

**Comment by coppit** [comment]
Sigh... And no sooner do I click send and the problem goes away. No DB
locking complains from gallerist, _and_ after starting and stopping
Photos.app, I see photolibraryd running again. Oh well. Unless that stack
trace means anything to you, I guess we can close this. I'll reopen later
if I see it again.

**Comment by koraktor** [comment]
The problem here is that the copying already needs a bit of data from the database. And it needs a lock for a short period of time.
For clarification, the copying is not done to prevent locking, but to reduce locking issues and to prevent interference with Photos and its background processes.

From my experience `photolibraryd` will lock from time to time.

**Comment by koraktor** [comment]
It seems that this got a lot better for me with OS X 10.11.1, i.e. Photos 1.2.

@coppit Can you test with that version?

**Comment by koraktor** [comment]
@coppit Would you mind testing the `no-lock` branch which essentially removes the need to lock the database at all.

I tested this with both, libraries not in use and currently opened in Photos. Which worked like expected all the time. I think there also might be some changes in Photos 1.2 (included with OS X 10.11.1) which might have improved the situation.
