### ISSUE TITLE
no such file or directory!?

### ISSUE THREAD

**Issue by PaulKeydel** [koraktor/gallerist#6]
Hi,
at first I must say that your idea of sharing photos via a web application is really great and thank you for programming this useful tool ;)
In my case unfortunately an error occurred while starting gallerist. It seems that gallerist can't open my photos library... Background:
I regularly backup the photos library with rsync from my MacBook to my Raspberry Pi (with Raspbian and an external HDD formatted with ext4, whereon the library is saved). A few days ago I came across your project and, of course, I wanted to try it out. Because of the fact that I leave my RasPi running 24/7 I decided to install the current version of ruby and gallerist on my RasPi instead of my Mac. This worked very well. So far, so good. But every time I start gallerist by typing
    gallerist -n /media/usbfestplatte/Fotos/Fotos-Mediathek.photoslibrary
I got the following error message (see screenshot)
    Errno::EN0ENT - No such file or directory @ realpath_rec - <path to photo database>
Although it is possible to browse to the gallerist website the only thing you can see is an error message :-(
![bildschirmfoto 2015-07-31 um 16 21 29](https://cloud.githubusercontent.com/assets/13593107/9016743/a3eda0cc-37d3-11e5-9b22-83c788d94e78.png)

**Comment by PaulKeydel** [comment]
Do you have a solution for this problem? Thanks in advance

**Comment by koraktor** [comment]
Can you post the result of `ls -l /media/usbfestplatte/Fotos/Fotos-Mediathek.photoslibrary`?

I guess there’s a `database` directory instead. As ext4 is case-sensitive and the code is trying to open `Database` this will fail. It seems that different versions of iPhoto/Photos use different cases for this folder. OS X’s HFS+ is case-insensitive by default, so it doesn’t fail on OS X.

As a workaround you might just want to rename or symlink the directory with the uppercase name.

**Comment by PaulKeydel** [comment]
![bildschirmfoto 2015-07-31 um 22 57 36](https://cloud.githubusercontent.com/assets/13593107/9017567/b88fb07a-37d7-11e5-9a2e-b1d023631e75.png)
members of the group sharing: pi (myself) and www-data (apache)

**Comment by PaulKeydel** [comment]
it seems that a simple "mv" in the terminal solves my problem ;)

**Comment by koraktor** [comment]
Ok, this should be fixed so it is automatically handled.

**Comment by koraktor** [comment]
Not yet. I leave this open to track this problem.
