### ISSUE TITLE
Fotos Version 3.0 (3291.13.210)

### ISSUE THREAD

**Issue by mro** [koraktor/gallerist#8]
seems to have changed the internal storage:

```bash
$ ls -l /Users/me/Pictures/Fotos-Mediathek.photoslibrary/database/
total 641728
-rw-r--r--@ 1 me  staff        452 31 Dez 16:11 DataModelVersion.plist
-rw-r--r--@ 1 me  admin     321536  9 Feb 18:45 RKAlbum_name.skindex
-rw-r--r--@ 1 me  admin      10240 23 Feb 00:35 RKMemory_title.skindex
-rw-r--r--@ 1 me  admin   13033472 23 Feb 00:35 RKVersion_searchIndexText.skindex
-rw-r--r--@ 1 me  staff      49152 31 Dez 16:03 metaSchema.db
-rw-r--r--@ 1 me  admin  313360384 23 Feb 13:05 photos.db
-rw-r--r--@ 1 me  admin    1775752 23 Feb 21:44 photos.db-wal
-rw-r--r--@ 1 me  admin        458 23 Feb 16:26 photos.db.lock
```

Are there still volunteers among the watchers and stargazers to help maintain this nice tool?

**Comment by koraktor** [comment]
Thanks for reporting.

I‘m aware that the code is incompatible with more recent versions of Photos. As Mojave already brings Photos 4.0 – and I don‘t have access to a system running High Sierra – I fear that I‘ll be unable to maintain support for older database schemas. The file layout is equal, though. So there‘s some chance that it might work as well.

**Comment by koraktor** [comment]
@mro I‘ve finally found some time to finish my changes. The code has been tested with libraries from Photos 4.0, but it also tries to be backwards compatible.

Please check if this works for you, too.
